routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

*/
// Route::get('/', function () {
//   return view('contents.home.index');
// });

Auth::routes();

Route::get('/', 'front_homeController@index')->name('front.home');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function()
{

	Route::resource('ocAddresses', 'oc_addressController');

	Route::resource('ocAffiliates', 'oc_affiliateController');

	Route::resource('ocAffiliateActivities', 'oc_affiliate_activityController');

	Route::resource('ocAffiliateLogins', 'oc_affiliate_loginController');

	Route::resource('ocAffiliateTransactions', 'oc_affiliate_transactionController');

	Route::resource('ocApis', 'oc_apiController');

	Route::resource('ocAttributes', 'oc_attributeController');

	Route::resource('ocAttributeDescriptions', 'oc_attribute_descriptionController');

	Route::resource('ocAttributeGroups', 'oc_attribute_groupController');

	Route::resource('ocAttributeGroupDescriptions', 'oc_attribute_group_descriptionController');

	Route::resource('ocBanners', 'oc_bannerController');

	Route::resource('ocBannerImages', 'oc_banner_imageController');

	Route::resource('ocBannerImageDescriptions', 'oc_banner_image_descriptionController');

	Route::resource('ocCategories', 'oc_categoryController');

	Route::resource('ocCategoryDescriptions', 'oc_category_descriptionController');

	Route::resource('ocCategoryFilters', 'oc_category_filterController');

	Route::resource('ocCategoryPaths', 'oc_category_pathController');

	Route::resource('ocCategoryToLayouts', 'oc_category_to_layoutController');

	Route::resource('ocCategoryToStores', 'oc_category_to_storeController');

	Route::resource('ocConfirms', 'oc_confirmController');

	Route::resource('ocConfirmToStores', 'oc_confirm_to_storeController');

	Route::resource('ocCountries', 'oc_countryController');

	Route::resource('ocCountryHpwds', 'oc_country_hpwdController');

	Route::resource('ocCoupons', 'oc_couponController');

	Route::resource('ocCouponCategories', 'oc_coupon_categoryController');

	Route::resource('ocCouponHistories', 'oc_coupon_historyController');

	Route::resource('ocCouponProducts', 'oc_coupon_productController');

	Route::resource('ocCurrencies', 'oc_currencyController');

	Route::resource('ocCustomers', 'oc_customerController');

	Route::resource('ocCustomerActivities', 'oc_customer_activityController');

	Route::resource('ocCustomerBanIps', 'oc_customer_ban_ipController');

	Route::resource('ocCustomerGroups', 'oc_customer_groupController');

	Route::resource('ocCustomerGroupDescriptions', 'oc_customer_group_descriptionController');

	Route::resource('ocCustomerHistories', 'oc_customer_historyController');

	Route::resource('ocCustomerIps', 'oc_customer_ipController');

	Route::resource('ocCustomerLogins', 'oc_customer_loginController');

	Route::resource('ocCustomerOnlines', 'oc_customer_onlineController');

	Route::resource('ocCustomerRewards', 'oc_customer_rewardController');

	Route::resource('ocCustomerTransactions', 'oc_customer_transactionController');

	Route::resource('ocCustomFields', 'oc_custom_fieldController');

	Route::resource('ocCustomFieldCustomerGroups', 'oc_custom_field_customer_groupController');

	Route::resource('ocCustomFieldDescriptions', 'oc_custom_field_descriptionController');

	Route::resource('ocCustomFieldValues', 'oc_custom_field_valueController');

	Route::resource('ocCustomFieldValueDescriptions', 'oc_custom_field_value_descriptionController');

	Route::resource('ocDownloads', 'oc_downloadController');

	Route::resource('ocDownloadDescriptions', 'oc_download_descriptionController');

	Route::resource('ocEvents', 'oc_eventController');

	Route::resource('ocExtensions', 'oc_extensionController');

	Route::resource('ocFilters', 'oc_filterController');

	Route::resource('ocFilterDescriptions', 'oc_filter_descriptionController');

	Route::resource('ocGeoZones', 'oc_geo_zoneController');

	Route::resource('ocInformations', 'oc_informationController');

	Route::resource('ocInformationDescriptions', 'oc_information_descriptionController');

	Route::resource('ocLanguages', 'oc_languageController');

	Route::resource('ocLayoutModules', 'oc_layout_moduleController');

	Route::resource('ocLayoutRoutes', 'oc_layout_routeController');

	Route::resource('ocLengthClassDescriptions', 'oc_length_class_descriptionController');

	Route::resource('ocLocations', 'oc_locationController');

	Route::resource('ocManufacturers', 'oc_manufacturerController');

	Route::resource('ocMarketings', 'oc_marketingController');

	Route::resource('ocModifications', 'oc_modificationController');

	Route::resource('ocModules', 'oc_moduleController');

	Route::resource('ocOptionValues', 'oc_option_valueController');

	Route::resource('ocOptionValueDescriptions', 'oc_option_value_descriptionController');

	Route::resource('ocOrders', 'oc_orderController');

	Route::resource('ocOrderCustomFields', 'oc_order_custom_fieldController');

	Route::resource('ocOrderHistories', 'oc_order_historyController');

	Route::resource('ocOrderOptions', 'oc_order_optionController');

	Route::resource('ocOrderProducts', 'oc_order_productController');

	Route::resource('ocOrderRecurrings', 'oc_order_recurringController');

	Route::resource('ocOrderRecurringTransactions', 'oc_order_recurring_transactionController');

	Route::resource('ocOrderTotals', 'oc_order_totalController');

	Route::resource('ocOrderVouchers', 'oc_order_voucherController');

	Route::resource('ocProducts', 'oc_productController');

	Route::resource('ocProductAttributes', 'oc_product_attributeController');

	Route::resource('ocProductDescriptions', 'oc_product_descriptionController');

	Route::resource('ocProductDiscounts', 'oc_product_discountController');

	Route::resource('ocProductImages', 'oc_product_imageController');

	Route::resource('ocProductOptions', 'oc_product_optionController');

	Route::resource('ocProductOptionValues', 'oc_product_option_valueController');

	Route::resource('ocProductRewards', 'oc_product_rewardController');

	Route::resource('ocProductSpecials', 'oc_product_specialController');

	Route::resource('ocRecurrings', 'oc_recurringController');

	Route::resource('ocReturns', 'oc_returnController');

	Route::resource('ocReturnHistories', 'oc_return_historyController');

	Route::resource('ocReviews', 'oc_reviewController');

	Route::resource('ocSettings', 'oc_settingController');

	Route::resource('ocStores', 'oc_storeController');

	Route::resource('ocTaxClasses', 'oc_tax_classController');

	Route::resource('ocTaxRates', 'oc_tax_rateController');

	Route::resource('ocTaxRules', 'oc_tax_ruleController');

	Route::resource('ocUploads', 'oc_uploadController');

	Route::resource('ocUsers', 'oc_userController');

	Route::resource('ocUserGroups', 'oc_user_groupController');

	Route::resource('ocVouchers', 'oc_voucherController');

	Route::resource('ocVoucherHistories', 'oc_voucher_historyController');

	Route::resource('ocWeightClassDescriptions', 'oc_weight_class_descriptionController');

	Route::resource('ocZones', 'oc_zoneController');

	Route::resource('ocZoneToGeoZones', 'oc_zone_to_geo_zoneController');

	Route::resource('users', 'userController');

	Route::resource('ocProducts', 'oc_productController');

	Route::resource('ocProductAttributes', 'oc_product_attributeController');

	Route::resource('ocProductDescriptions', 'oc_product_descriptionController');

	Route::resource('ocProductDiscounts', 'oc_product_discountController');

	Route::resource('ocCustomerGroupDescriptions', 'oc_customer_group_descriptionController');

	Route::resource('ocProductToCategories', 'oc_product_to_categoryController');

	Route::resource('ocProductToDownloads', 'oc_product_to_downloadController');

	Route::resource('ocProductToLayouts', 'oc_product_to_layoutController');

	Route::resource('ocProductToStores', 'oc_product_to_storeController');

	Route::resource('ocCategoryDescriptions', 'oc_category_descriptionController');

	Route::resource('ocProductToCategories', 'oc_product_to_categoryController');

});


Route::group(['prefix' => '/cart'], function() {
	Route::get('/', 'front_categoryController@cart')->name('front.cart');
	Route::post('/add', 'front_categoryController@add')->name('cart.add');
	Route::get('/clear', 'front_categoryController@clear')->name('cart.clear');
	Route::post('/remove/{id}', 'front_categoryController@remove')->name('cart.remove');
	Route::post('/update/{id}', 'front_categoryController@update')->name('cart.update');
});

Route::get('/{category}', 'front_categoryController@show')->name('front.category');

app/Models/oc_setting.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class oc_setting
 * @package App\Models
 * @version August 26, 2017, 8:02 am UTC
 *
 * @property integer store_id
 * @property string code
 * @property string key
 * @property string value
 * @property boolean serialized
 */
class oc_setting extends Model
{
    use SoftDeletes;

    public $table = 'oc_setting';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'store_id',
        'code',
        'key',
        'value',
        'serialized'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'setting_id' => 'integer',
        'store_id' => 'integer',
        'code' => 'string',
        'key' => 'string',
        'value' => 'string',
        'serialized' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/oc_settingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createoc_settingRequest;
use App\Http\Requests\Updateoc_settingRequest;
use App\Repositories\oc_settingRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class oc_settingController extends AppBaseController
{
    /** @var  oc_settingRepository */
    private $ocSettingRepository;

    public function __construct(oc_settingRepository $ocSettingRepo)
    {
        $this->ocSettingRepository = $ocSettingRepo;
    }

    /**
     * Display a listing of the oc_setting.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ocSettingRepository->pushCriteria(new RequestCriteria($request));
        $ocSettings = $this->ocSettingRepository->paginate(20);

        return view('oc_settings.index')
            ->with('ocSettings', $ocSettings);
    }

    /**
     * Show the form for creating a new oc_setting.
     *
     * @return Response
     */
    public function create()
    {
        return view('oc_settings.create');
    }

    /**
     * Store a newly created oc_setting in storage.
     *
     * @param Createoc_settingRequest $request
     *
     * @return Response
     */
    public function store(Createoc_settingRequest $request)
    {
        $input = $request->all();

        $ocSetting = $this->ocSettingRepository->create($input);

        Flash::success('Oc Setting saved successfully.');

        return redirect(route('ocSettings.index'));
    }

    /**
     * Display the specified oc_setting.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ocSetting = $this->ocSettingRepository->findWithoutFail($id);

        if (empty($ocSetting)) {
            Flash::error('Oc Setting not found');

            return redirect(route('ocSettings.index'));
        }

        return view('oc_settings.show')->with('ocSetting', $ocSetting);
    }

    /**
     * Show the form for editing the specified oc_setting.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ocSetting = $this->ocSettingRepository->findWithoutFail($id);

        if (empty($ocSetting)) {
            Flash::error('Oc Setting not found');

            return redirect(route('ocSettings.index'));
        }

        return view('oc_settings.edit')->with('ocSetting', $ocSetting);
    }

    /**
     * Update the specified oc_setting in storage.
     *
     * @param  int              $id
     * @param Updateoc_settingRequest $request
     *
     * @return Response
     */
    public function update($id, Updateoc_settingRequest $request)
    {
        $ocSetting = $this->ocSettingRepository->findWithoutFail($id);

        if (empty($ocSetting)) {
            Flash::error('Oc Setting not found');

            return redirect(route('ocSettings.index'));
        }

        $ocSetting = $this->ocSettingRepository->update($request->all(), $id);

        Flash::success('Oc Setting updated successfully.');

        return redirect(route('ocSettings.index'));
    }

    /**
     * Remove the specified oc_setting from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ocSetting = $this->ocSettingRepository->findWithoutFail($id);

        if (empty($ocSetting)) {
            Flash::error('Oc Setting not found');

            return redirect(route('ocSettings.index'));
        }

        $this->ocSettingRepository->delete($id);

        Flash::success('Oc Setting deleted successfully.');

        return redirect(route('ocSettings.index'));
    }
}

resources/views/oc_settings/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Setting
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ocSettings.store']) !!}

                        @include('oc_settings.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/oc_settings/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Setting
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ocSetting, ['route' => ['ocSettings.update', $ocSetting->id], 'method' => 'patch']) !!}

                        @include('oc_settings.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/oc_settings/fields.blade.php
<!-- Store Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('store_id', 'Store Id:') !!}
    {!! Form::number('store_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('code', 'Code:') !!}
    {!! Form::text('code', null, ['class' => 'form-control']) !!}
</div>

<!-- Key Field -->
<div class="form-group col-sm-6">
    {!! Form::label('key', 'Key:') !!}
    {!! Form::text('key', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::textarea('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Serialized Field -->
<div class="form-group col-sm-6">
    {!! Form::label('serialized', 'Serialized:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('serialized', false) !!}
        {!! Form::checkbox('serialized', '1', null) !!} 1
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ocSettings.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/oc_settings/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Oc Settings</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ocSettings.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('oc_settings.table')
            </div>
        </div>
    </div>
@endsection

resources/views/oc_settings/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Setting
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('oc_settings.show_fields')
                    <a href="{!! route('ocSettings.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/oc_settings/show_fields.blade.php
<!-- Setting Id Field -->
<div class="form-group">
    {!! Form::label('setting_id', 'Setting Id:') !!}
    <p>{!! $ocSetting->setting_id !!}</p>
</div>

<!-- Store Id Field -->
<div class="form-group">
    {!! Form::label('store_id', 'Store Id:') !!}
    <p>{!! $ocSetting->store_id !!}</p>
</div>

<!-- Code Field -->
<div class="form-group">
    {!! Form::label('code', 'Code:') !!}
    <p>{!! $ocSetting->code !!}</p>
</div>

<!-- Key Field -->
<div class="form-group">
    {!! Form::label('key', 'Key:') !!}
    <p>{!! $ocSetting->key !!}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{!! $ocSetting->value !!}</p>
</div>

<!-- Serialized Field -->
<div class="form-group">
    {!! Form::label('serialized', 'Serialized:') !!}
    <p>{!! $ocSetting->serialized !!}</p>
</div>

resources/views/oc_settings/table.blade.php
<table class="table table-responsive" id="ocSettings-table">
    <thead>
        <th>Store Id</th>
        <th>Code</th>
        <th>Key</th>
        <th>Value</th>
        <th>Serialized</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($ocSettings as $ocSetting)
        <tr>
            <td>{!! $ocSetting->store_id !!}</td>
            <td>{!! $ocSetting->code !!}</td>
            <td>{!! $ocSetting->key !!}</td>
            <td>{!! $ocSetting->value !!}</td>
            <td>{!! $ocSetting->serialized !!}</td>
            <td>
                {!! Form::open(['route' => ['ocSettings.destroy', $ocSetting->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('ocSettings.show', [$ocSetting->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('ocSettings.edit', [$ocSetting->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>