routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

*/
// Route::get('/', function () {
//   return view('contents.home.index');
// });

Auth::routes();

Route::get('/', 'front_homeController@index')->name('front.home');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function()
{

	Route::resource('ocAddresses', 'oc_addressController');

	Route::resource('ocAffiliates', 'oc_affiliateController');

	Route::resource('ocAffiliateActivities', 'oc_affiliate_activityController');

	Route::resource('ocAffiliateLogins', 'oc_affiliate_loginController');

	Route::resource('ocAffiliateTransactions', 'oc_affiliate_transactionController');

	Route::resource('ocApis', 'oc_apiController');

	Route::resource('ocAttributes', 'oc_attributeController');

	Route::resource('ocAttributeDescriptions', 'oc_attribute_descriptionController');

	Route::resource('ocAttributeGroups', 'oc_attribute_groupController');

	Route::resource('ocAttributeGroupDescriptions', 'oc_attribute_group_descriptionController');

	Route::resource('ocBanners', 'oc_bannerController');

	Route::resource('ocBannerImages', 'oc_banner_imageController');

	Route::resource('ocBannerImageDescriptions', 'oc_banner_image_descriptionController');

	Route::resource('ocCategories', 'oc_categoryController');

	Route::resource('ocCategoryDescriptions', 'oc_category_descriptionController');

	Route::resource('ocCategoryFilters', 'oc_category_filterController');

	Route::resource('ocCategoryPaths', 'oc_category_pathController');

	Route::resource('ocCategoryToLayouts', 'oc_category_to_layoutController');

	Route::resource('ocCategoryToStores', 'oc_category_to_storeController');

	Route::resource('ocConfirms', 'oc_confirmController');

	Route::resource('ocConfirmToStores', 'oc_confirm_to_storeController');

	Route::resource('ocCountries', 'oc_countryController');

	Route::resource('ocCountryHpwds', 'oc_country_hpwdController');

	Route::resource('ocCoupons', 'oc_couponController');

	Route::resource('ocCouponCategories', 'oc_coupon_categoryController');

	Route::resource('ocCouponHistories', 'oc_coupon_historyController');

	Route::resource('ocCouponProducts', 'oc_coupon_productController');

	Route::resource('ocCurrencies', 'oc_currencyController');

	Route::resource('ocCustomers', 'oc_customerController');

	Route::resource('ocCustomerActivities', 'oc_customer_activityController');

	Route::resource('ocCustomerBanIps', 'oc_customer_ban_ipController');

	Route::resource('ocCustomerGroups', 'oc_customer_groupController');

	Route::resource('ocCustomerGroupDescriptions', 'oc_customer_group_descriptionController');

	Route::resource('ocCustomerHistories', 'oc_customer_historyController');

	Route::resource('ocCustomerIps', 'oc_customer_ipController');

	Route::resource('ocCustomerLogins', 'oc_customer_loginController');

	Route::resource('ocCustomerOnlines', 'oc_customer_onlineController');

	Route::resource('ocCustomerRewards', 'oc_customer_rewardController');

	Route::resource('ocCustomerTransactions', 'oc_customer_transactionController');

	Route::resource('ocCustomFields', 'oc_custom_fieldController');

	Route::resource('ocCustomFieldCustomerGroups', 'oc_custom_field_customer_groupController');

	Route::resource('ocCustomFieldDescriptions', 'oc_custom_field_descriptionController');

	Route::resource('ocCustomFieldValues', 'oc_custom_field_valueController');

	Route::resource('ocCustomFieldValueDescriptions', 'oc_custom_field_value_descriptionController');

	Route::resource('ocDownloads', 'oc_downloadController');

	Route::resource('ocDownloadDescriptions', 'oc_download_descriptionController');

	Route::resource('ocEvents', 'oc_eventController');

	Route::resource('ocExtensions', 'oc_extensionController');

	Route::resource('ocFilters', 'oc_filterController');

	Route::resource('ocFilterDescriptions', 'oc_filter_descriptionController');

	Route::resource('ocGeoZones', 'oc_geo_zoneController');

	Route::resource('ocInformations', 'oc_informationController');

	Route::resource('ocInformationDescriptions', 'oc_information_descriptionController');

	Route::resource('ocLanguages', 'oc_languageController');

	Route::resource('ocLayoutModules', 'oc_layout_moduleController');

	Route::resource('ocLayoutRoutes', 'oc_layout_routeController');

	Route::resource('ocLengthClassDescriptions', 'oc_length_class_descriptionController');

	Route::resource('ocLocations', 'oc_locationController');

	Route::resource('ocManufacturers', 'oc_manufacturerController');

	Route::resource('ocMarketings', 'oc_marketingController');

	Route::resource('ocModifications', 'oc_modificationController');

	Route::resource('ocModules', 'oc_moduleController');

	Route::resource('ocOptionValues', 'oc_option_valueController');

	Route::resource('ocOptionValueDescriptions', 'oc_option_value_descriptionController');

	Route::resource('ocOrders', 'oc_orderController');

	Route::resource('ocOrderCustomFields', 'oc_order_custom_fieldController');

	Route::resource('ocOrderHistories', 'oc_order_historyController');

	Route::resource('ocOrderOptions', 'oc_order_optionController');

	Route::resource('ocOrderProducts', 'oc_order_productController');

	Route::resource('ocOrderRecurrings', 'oc_order_recurringController');

	Route::resource('ocOrderRecurringTransactions', 'oc_order_recurring_transactionController');

	Route::resource('ocOrderTotals', 'oc_order_totalController');

	Route::resource('ocOrderVouchers', 'oc_order_voucherController');

	Route::resource('ocProducts', 'oc_productController');

	Route::resource('ocProductAttributes', 'oc_product_attributeController');

	Route::resource('ocProductDescriptions', 'oc_product_descriptionController');

	Route::resource('ocProductDiscounts', 'oc_product_discountController');

	Route::resource('ocProductImages', 'oc_product_imageController');

	Route::resource('ocProductOptions', 'oc_product_optionController');

	Route::resource('ocProductOptionValues', 'oc_product_option_valueController');

	Route::resource('ocProductRewards', 'oc_product_rewardController');

	Route::resource('ocProductSpecials', 'oc_product_specialController');

	Route::resource('ocRecurrings', 'oc_recurringController');

	Route::resource('ocReturns', 'oc_returnController');

	Route::resource('ocReturnHistories', 'oc_return_historyController');

	Route::resource('ocReviews', 'oc_reviewController');

	Route::resource('ocSettings', 'oc_settingController');

	Route::resource('ocStores', 'oc_storeController');

	Route::resource('ocTaxClasses', 'oc_tax_classController');

	Route::resource('ocTaxRates', 'oc_tax_rateController');

	Route::resource('ocTaxRules', 'oc_tax_ruleController');

	Route::resource('ocUploads', 'oc_uploadController');

	Route::resource('ocUsers', 'oc_userController');

	Route::resource('ocUserGroups', 'oc_user_groupController');

	Route::resource('ocVouchers', 'oc_voucherController');

	Route::resource('ocVoucherHistories', 'oc_voucher_historyController');

	Route::resource('ocWeightClassDescriptions', 'oc_weight_class_descriptionController');

	Route::resource('ocZones', 'oc_zoneController');

	Route::resource('ocZoneToGeoZones', 'oc_zone_to_geo_zoneController');

	Route::resource('users', 'userController');

	Route::resource('ocProducts', 'oc_productController');

	Route::resource('ocProductAttributes', 'oc_product_attributeController');

	Route::resource('ocProductDescriptions', 'oc_product_descriptionController');

	Route::resource('ocProductDiscounts', 'oc_product_discountController');

	Route::resource('ocCustomerGroupDescriptions', 'oc_customer_group_descriptionController');

	Route::resource('ocProductToCategories', 'oc_product_to_categoryController');

	Route::resource('ocProductToDownloads', 'oc_product_to_downloadController');

	Route::resource('ocProductToLayouts', 'oc_product_to_layoutController');

	Route::resource('ocProductToStores', 'oc_product_to_storeController');

	Route::resource('ocCategoryDescriptions', 'oc_category_descriptionController');

	Route::resource('ocProductToCategories', 'oc_product_to_categoryController');

});


Route::group(['prefix' => '/cart'], function() {
	Route::get('/', 'front_categoryController@cart')->name('front.cart');
	Route::post('/add', 'front_categoryController@add')->name('cart.add');
	Route::get('/clear', 'front_categoryController@clear')->name('cart.clear');
	Route::post('/remove/{id}', 'front_categoryController@remove')->name('cart.remove');
	Route::post('/update/{id}', 'front_categoryController@update')->name('cart.update');
});

Route::get('/{category}', 'front_categoryController@show')->name('front.category');

app/Models/oc_product_image.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class oc_product_image
 * @package App\Models
 * @version August 26, 2017, 8:01 am UTC
 *
 * @property integer product_id
 * @property string image
 * @property integer sort_order
 */
class oc_product_image extends Model
{
    use SoftDeletes;

    public $table = 'oc_product_image';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'product_id',
        'image',
        'sort_order'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'product_image_id' => 'integer',
        'product_id' => 'integer',
        'image' => 'string',
        'sort_order' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/oc_product_imageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createoc_product_imageRequest;
use App\Http\Requests\Updateoc_product_imageRequest;
use App\Repositories\oc_product_imageRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class oc_product_imageController extends AppBaseController
{
    /** @var  oc_product_imageRepository */
    private $ocProductImageRepository;

    public function __construct(oc_product_imageRepository $ocProductImageRepo)
    {
        $this->ocProductImageRepository = $ocProductImageRepo;
    }

    /**
     * Display a listing of the oc_product_image.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ocProductImageRepository->pushCriteria(new RequestCriteria($request));
        $ocProductImages = $this->ocProductImageRepository->paginate(20);

        return view('oc_product_images.index')
            ->with('ocProductImages', $ocProductImages);
    }

    /**
     * Show the form for creating a new oc_product_image.
     *
     * @return Response
     */
    public function create()
    {
        return view('oc_product_images.create');
    }

    /**
     * Store a newly created oc_product_image in storage.
     *
     * @param Createoc_product_imageRequest $request
     *
     * @return Response
     */
    public function store(Createoc_product_imageRequest $request)
    {
        if ($request->file('image')) {
            $file       = $request->file('image');
            $fileName   = $file->getClientOriginalName();
            $request->file('image')->move("image/product/".$request->product_id."/", $fileName);


        }
        else {
            $fileName = 'default.jpg';
        }
        $input = $request->all();

        $input['image'] = $fileName;
        $ocProductImage = $this->ocProductImageRepository->create($input);
        
        Flash::success('Oc Product Image saved successfully.');

        return redirect(route('ocProductImages.index'));
    }

    /**
     * Display the specified oc_product_image.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ocProductImage = $this->ocProductImageRepository->findWithoutFail($id);

        if (empty($ocProductImage)) {
            Flash::error('Oc Product Image not found');

            return redirect(route('ocProductImages.index'));
        }

        return view('oc_product_images.show')->with('ocProductImage', $ocProductImage);
    }

    /**
     * Show the form for editing the specified oc_product_image.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ocProductImage = $this->ocProductImageRepository->findWithoutFail($id);

        if (empty($ocProductImage)) {
            Flash::error('Oc Product Image not found');

            return redirect(route('ocProductImages.index'));
        }

        return view('oc_product_images.edit')->with('ocProductImage', $ocProductImage);
    }

    /**
     * Update the specified oc_product_image in storage.
     *
     * @param  int              $id
     * @param Updateoc_product_imageRequest $request
     *
     * @return Response
     */
    public function update($id, Updateoc_product_imageRequest $request)
    {
        $ocProductImage = $this->ocProductImageRepository->findWithoutFail($id);
        if ($request->file('image')) {
            $file       = $request->file('image');
            $fileName   = $file->getClientOriginalName();
            $request->file('image')->move("image/product/".$request->product_id."/", $fileName);
        }
        else {
            $fileName = 'default.jpg';
        }
        $input = $request->all();

        $input['image'] = $fileName;

        if (empty($ocProductImage)) {
            Flash::error('Oc Product Image not found');

            return redirect(route('ocProductImages.index'));
        }

        $ocProductImage = $this->ocProductImageRepository->update($input, $id);

        Flash::success('Oc Product Image updated successfully.');

        return redirect(route('ocProductImages.index'));
    }

    /**
     * Remove the specified oc_product_image from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ocProductImage = $this->ocProductImageRepository->findWithoutFail($id);

        if (empty($ocProductImage)) {
            Flash::error('Oc Product Image not found');

            return redirect(route('ocProductImages.index'));
        }

        $this->ocProductImageRepository->delete($id);

        Flash::success('Oc Product Image deleted successfully.');

        return redirect(route('ocProductImages.index'));
    }
}

resources/views/oc_product_images/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Product Image
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ocProductImages.store', 'files' => true]) !!}

                        @include('oc_product_images.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#showgambar').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#image").change(function () {
        readURL(this);
    });

</script>
@endsection

resources/views/oc_product_images/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Product Image
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ocProductImage, ['route' => ['ocProductImages.update', $ocProductImage->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('oc_product_images.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/oc_product_images/fields.blade.php
<!-- Product Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('product_id', 'Product:') !!}
    @php $items = App\Models\oc_product::has('detail')->get(); @endphp
    <select class="form-control" id="product_id" name="product_id">
    @foreach($items as $i)
    <option value="{{$i->id}}">{{ App\Models\oc_product_description::find($i->id)->name }}</option>
    @endforeach
    </select>
</div>
<div class="form-group col-sm-6">
<img src="http://placehold.it/250x250" id="showgambar" style="max-width:400px;max-height:400px;float:left;" />
</div>
<!-- Image Field -->
<div class="form-group col-sm-12">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image',null,array('id'=>'image','class'=>'form-control')) !!}
</div>

<!-- Sort Order Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sort_order', 'Sort Order:') !!}
    {!! Form::number('sort_order', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ocProductImages.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/oc_product_images/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Oc Product Images</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ocProductImages.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('oc_product_images.table')
            </div>
        </div>
    </div>
@endsection

resources/views/oc_product_images/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Oc Product Image
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('oc_product_images.show_fields')
                    <a href="{!! route('ocProductImages.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/oc_product_images/show_fields.blade.php
<!-- Product Image Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $ocProductImage->id !!}</p>
</div>

<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product_id', 'Product Id:') !!}
    <p>{!! App\Models\oc_product_description::find($ocProductImage->product_id)->name !!}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{!! $ocProductImage->image !!}</p>
</div>

<!-- Sort Order Field -->
<div class="form-group">
    {!! Form::label('sort_order', 'Sort Order:') !!}
    <p>{!! $ocProductImage->sort_order !!}</p>
</div>

resources/views/oc_product_images/table.blade.php
<table class="table table-responsive" id="ocProductImages-table">
    <thead>
        <th>Product</th>
        <th>Image</th>
        <th>Sort Order</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($ocProductImages as $ocProductImage)
        <tr>
            <td>{!! App\Models\oc_product_description::where('product_id', $ocProductImage->product_id)->first()->name !!}</td>
            <td><img src="{!! 'image/product/'.$ocProductImage->product_id.'/'.$ocProductImage->image !!}" alt="Image" width="150" height="100"></td>
            <td>{!! $ocProductImage->sort_order !!}</td>
            <td>
                {!! Form::open(['route' => ['ocProductImages.destroy', $ocProductImage->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('ocProductImages.show', [$ocProductImage->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('ocProductImages.edit', [$ocProductImage->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>